export const FETCH_POLLUTED_CITIES = "FETCH_POLLUTED_CITIES";
export const FETCH_POLLUTED_CITIES_SUCCESS = "FETCH_POLLUTED_CITIES_SUCCESS";
export const FETCH_POLLUTED_CITIES_FAILED = "FETCH_POLLUTED_CITIES_FAILED";

export const FETCH_CITY_DETAILS = "FETCH_CITY_DETAILS";
export const FETCH_CITY_DETAILS_SUCCESS = "FETCH_CITY_DETAILS_SUCCESS";
export const FETCH_CITY_DETAILS_FAILED = "FETCH_CITY_DETAILS_FAILED";

