export const FETCH_POLLUTED_CITIES = "FETCH_POLLUTED_CITIES";
export const FETCH_POLLUTED_CITIES_SUCCESS = "FETCH_POLLUTED_CITIES_SUCCESS";
export const FETCH_POLLUTED_CITIES_FAILED = "FETCH_POLLUTED_CITIES_FAILED";

